shop_homepage:
    path:     /
    defaults: { _controller: "ShopBundle:Category:index" }
    requirements:
            page: '\d+'

shop_category_show:
    path:     /category/{name}
    defaults: { _controller: "ShopBundle:Category:show" }
    methods:  GET
