services:
#    shop.example:
#        class: ShopBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
    shop.symshop.admin.category:
        class: ShopBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Category, label: Category }
        arguments: [null, ShopBundle\Entity\Category, ShopBundle:CategoryAdmin]
    shop.symshop.admin.product:
        class: ShopBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Products, label: Product }
        arguments: [null, ShopBundle\Entity\Product, ShopBundle:ProductAdmin]